# errata:
# - sudo/dist/group are set so as to get Blue Box VMs, necessary for [loopback]
#   IPv6 support

sudo: required
dist: trusty

os: linux
language: generic

addons:
  apt:
    packages:
      # Use more recent docker version
      - docker-ce
      # Can be removed if Travis ever upgrades to Bionic
      - realpath

services:
  - docker

cache:
  apt: true
  ccache: true
  directories:
    - depends/built
    - depends/sdk-sources
    # Use .ccache-ci so that we don't mix ccache dirs with local ccache dir when doing local testing
    - $HOME/.ccache-ci
    - $HOME/docker

env:
  global:
    # DOCKER_HUB_USER
    - secure: "J0T+zrRBBzBnxoioCD378cRSJUF8Vms32QMmrENVVfuJl03oBQv0QxSatLEiD4PtRPrN00mJ8/k/HdqFQ0SN1yg6a00duOZ6C9jk6t/fExBO1LNhp3Z7lcaMUrNEyRN6sgfVeznDVTGj9jBQU2HNlwHk0UD9BNp/k+Bjhrtw7Njp9JTLZKBgxrXk0WZmfk0d75Q+9DajA1j2tSfWVpwzv6HMGfqIH1wsVEakBY+tnaE6EO3IdzdWHhf/iV+Tx0tL0Qz/6mejgSuoGLTJLmeTrceTTmsDlN3B95y+XfcYDs6EP7gpzN8Ffg/mLV8xJ2Myj7+b1o+smMJZE5tLuPIeAu0YsfkPNa/tNLotOlDxF72per0kXyNYbRf+JrpxiOu9pLCtdtd40V2SsiNhpQqHVy+b+wkkqo2syTHT+9UNkqEi3WFm6TqFuOeQNtDm6R0hRl/Talw/ZEeKs68z1Cf6VyBrZG5LqtOurtWlKwXCe/Tr1i2g4BEAcbywphtCCcfgMK9YSGQnjKkGk6k9gVEa2bneYLZz1RSh2OpXnIsIJOX7X0hNd5xtQDLgbpSUlKwVcEriWeGe12GCszKNX9gdEo2bHeq4xAJ6BE+ot745z9dc+nC2BJ6Su+I5L6zBg4m2FWn0TWhPvz/6JR26t6ls/E7m+hkwJTCHnIUiFmmzpEw="
    # DOCKER_HUB_PASSWORD
    - secure: "RLzlMhfLqwSBrZqJOVOd61suXBn+HtUR3vOZfuFYF/Qmjjj5TE41+rObZmzc54hP/ZL+OH6blnibpvfDXlX+eN38ivFQfuxkJIGL68SJsEwNBRwW39Yw6Hl5RdI41MLCH7ByN15wifLp1JKBilHJ7XGMOUjI7P0yl7JjX8GBXUCtJbVLRugo80/yn+XQ1NdnlpbpYHNjMEQFWSODPa3pSK5McWvyQjDZDgS+IkdrZmIYJPMa7bmKH5I/edUPSmXQT905FgEwq9u8XR0SyBopli21EK9l6GkXIIvmDTYz5vT26Apvi2B4Aoazlklg+KNRUJuLGerpt6kbnU0gMSUChVkFfFhOk6GRSN3a/AUfD2FOudvMhet2QvlPHx+GYdEUr5XVo5HW42pHsqfD6eDtHd8VLTsHP0q4C8V85fNMv21lkkehy2ry8fx/RRy6x4O2wg2mua+79UkGKXp75gMKzWEcth34PCFCOu37l2F8R/ANnrQ52K/8vIQ88TtU2OpYX89fHjLojBxu+WKEBGZH2LRPsZBOUHeeO5C/xKDrhZU24ORnMW8wg66Qg5GIX1KI4a8yp73Mpues5hzpJ6wkMuRrQt40ymKndLCjv8KSd+5BfP6Or/KIrzDNYdZaasjk7JNi6rcZmm9d3fTAo+Ja/mjpUCIOo3SX14luzVCJIig="
    - RUN_TESTS=false
    - DOCKER_BUILD=false

  matrix:
    - BUILD_TARGET=arm-linux
    - BUILD_TARGET=win32 RUN_TESTS=true
    - BUILD_TARGET=win64 RUN_TESTS=true
    - BUILD_TARGET=linux32 RUN_TESTS=true
    - BUILD_TARGET=linux64 RUN_TESTS=true
    - BUILD_TARGET=linux64_nowallet
    - BUILD_TARGET=linux64_release DOCKER_BUILD=true
    - BUILD_TARGET=mac

before_cache:
  # Save builder image
  - docker save polis-builder-$BUILD_TARGET $(docker history -q polis-builder-$BUILD_TARGET | grep -v \<missing\>) | gzip -2 > $HOME/docker/polis-builder-$BUILD_TARGET.tar.gz

install:
    # Load cached builder image
    - if [ -f $HOME/docker/polis-builder-$BUILD_TARGET.tar.gz ]; then zcat $HOME/docker/polis-builder-$BUILD_TARGET.tar.gz | docker load || true; fi
    - ./ci/build_builder.sh
#    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
before_script:
    # Make sure stdout is in blocking mode. Otherwise builds will fail due to large writes to stdout
    # See https://github.com/travis-ci/travis-ci/issues/4704. If this gets fixed, this line can also be removed.
    - python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
script:
    - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
    # Our scripts try to be Travis agnostic
    - export PULL_REQUEST="$TRAVIS_PULL_REQUEST"
    - export JOB_NUMBER="$TRAVIS_JOB_NUMBER"
    - export BUILD_DIR="$TRAVIS_BUILD_DIR"
    # We split this up into multiple stages to keep Travis logs per command smaller
    - ./ci/build_depends.sh
    - ./ci/build_src.sh
    - if [ "$RUN_TESTS" = "true" ]; then travis_wait 30 ./ci/test_unittests.sh; fi
    - if [ "$RUN_TESTS" = "true" ]; then ./ci/test_integrationtests.sh; fi
    - if [ "$DOCKER_BUILD" = "true" ]; then BUILD_DIR=build-ci/poliscore-$BUILD_TARGET ./docker/build-docker.sh; fi
after_script:
    - echo $TRAVIS_COMMIT_RANGE
    - echo $TRAVIS_COMMIT_LOG
after_success:
    - if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "develop" -a "$DOCKER_BUILD" = "true" ]; then docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD && ./docker/push-docker.sh; fi
